### ISSUE TITLE
Small difference observed in the normalized X and Y signals between GenomeStudio vs Illumina:BeadArrayFiles

### ISSUE THREAD

**Issue by Gerbenvandervries** [Illumina/BeadArrayFiles#14]
I have a question about a small difference I observe in  the normalized X and Y signals in final reports generated with GenomeStudio vs the illumina autocovert tool + python package IlluminaBeadArrayFiles::GenotypeCalls . I analyzed 96 samples on a GSA array GSAMD-24v1-0_20011747_A5. For 99.9 % of the snps the X and Y signals are exactly the same. But for about a 100 snps the X and Y signals differ, where the X_RAW and Y_RAW number are the same.

Genome Studio results:
SNP | X_RAW | Y_RAW | X | Y
-- | -- | -- | -- | --
GSA-21:9871186 | 7248 | 2236 | 1.173 | 0.326
GSA-21:9952707 | 6435 | 2797 | 1.036 | 0.421
GSA-rs1006435 | 5119 | 2310 | 0.813 | 0.338

Illumina:BeadArrayFiles tool results for the same snps:  
-- | -- | -- | -- | --
SNP | X_RAW | Y_RAW | X | Y
GSA-21:9871186 | 7248 | 2236 | 1.385 | 0.433
GSA-21:9952707 | 6435 | 2797 | 1.230 | 0.542
GSA-rs1006435 | 5119 | 2310 | 0.978 | 0.448

As you can see, the X_RAW and Y_RAW number are the same, but the normalized X and Y differ. Do you have an explanation why we see this, only for a small number of snps?

**Comment by KelleyRyanM** [comment]
@Gerbenvandervries,
  The expectation is that these should be identical. Can you confirm which version of GenomeStudio and AutoConvert are used?

**Comment by Gerbenvandervries** [comment]
BeadArrayFiles/1.3.1 and GenomeStudio 2011.1

**Comment by KelleyRyanM** [comment]
Do you know which version of AutoConvert or AutoCall was used to create the GTC files?

**Comment by Gerbenvandervries** [comment]
version 2.0.1.179
