### ISSUE TITLE
Determining log r ratio and b allele frequency

### ISSUE THREAD

**Issue by palijmath** [Illumina/BeadArrayFiles#2]
Can this program be used to determine log r ratios and b allele frequencies? I have a set of .gtc files from an Illumina BeadChip run, and their corresponding manifest file in .bpm format. I’m interested in determining the log r ratios and b allele frequencies for each SNP, but when I use the applicable GenotypeCalls functions those values are returned as zeroes. I see how to use the NormalizationTransform functions to get the normalized x and y values, and the R and theta values from those. What would be the recommended next steps to obtain the log r ratios and b allele frequencies?

**Comment by KelleyRyanM** [comment]
Do you have access to the original IDAT files used to generate these GTC files? I believe the AutoConvert 2.0 version software will populate these fields when creating the GTC file.
