### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by cmccabe0728** [Illumina/BeadArrayFiles#40]
Will support for python 3 be added? Thank you.

**Comment by jzieve** [comment]
It should work with python3 (i.e., https://github.com/Illumina/BeadArrayFiles?tab=readme-ov-file#compatibility).
Are you seeing something different?

**Comment by cmccabe0728** [comment]
I haven't tried I just noticed I am on a python 2.7 install, let me try on 3.... thank you.

**Comment by cmccabe0728** [comment]
executed in python3 with no issues
